# Generated by Django 4.2 on 2024-06-29 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='upload_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
