# Generated by Django 4.2 on 2024-06-30 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hhcr', '0002_document_upload_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='predicted_document',
            field=models.FileField(default='out.jpg', upload_to='predicted_image'),
        ),
    ]
